name = "ImplicitCutIntegration"
uuid = "f4391067-c08d-4a75-95e8-189e864e8de7"
authors = ["PenguinxCutCell"]
version = "0.1.0"

[deps]
ImplicitIntegration = "bc256489-3a69-4a66-afc4-127cc87e6182"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
SparseArrays = "2f01184e-e22b-5df5-ae63-d93ebab69eaf"
StaticArrays = "90137ffa-7385-5640-81b9-e52037218182"
Statistics = "10745b16-79ce-11e8-11f9-7d13ad32a3b2"

[compat]
ImplicitIntegration = "0.2"
StaticArrays = "1"
julia = "1.10"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
